
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xkalmanfilterkernel.h"

/*
* The configuration table for devices
*/

XKalmanfilterkernel_Config XKalmanfilterkernel_ConfigTable[XPAR_XKALMANFILTERKERNEL_NUM_INSTANCES] =
{
	{
		XPAR_KALMANFILTERKERNEL_0_DEVICE_ID,
		XPAR_KALMANFILTERKERNEL_0_S_AXI_AXI_CPU_BASEADDR
	}
};


